### ISSUE TITLE
not found plyfile

### ISSUE THREAD

**Issue by zeroStrong** [USTC3DV/NDR-code#1]
Thanks for the great work.

I am having trouble generating a ply file when I run this command
`python geo_render.py ./datasets/kfusion_frog/ ./exp/kfusion_frog/result/ 120000`

> RuntimeError: File could not be read: ./exp/kfusion_frog/result/validations_meshes/00120000_0.ply

 I'd like to know what the solution is.

Thanks.

**Comment by RainbowRui** [comment]
['./geo_render.py'](https://github.com/USTC3DV/NDR-code/blob/main/geo_render.py) is a script for rendering reconstructed geometry to the image. So firstly you need to obtain the results, such as evaluating pre-trained model or training from the ground up.

**Comment by zeroStrong** [comment]
I solved the problem by running this command first!
`python pretrained_eval.py`
Thanks!!
I Close this issue
