### ISSUE TITLE
Self-collected plant dataset

### ISSUE THREAD

**Issue by YuePanEdward** [USTC3DV/NDR-code#10]
Thanks for your great work.
I wonder if you can also share the self-collected plant dataset? I am considering doing some 4D reconstruction experiments for agricultural applications. I think this plant dataset can be a good starting point for prototyping.

**Comment by RainbowRui** [comment]
The link is here: https://drive.google.com/file/d/13LM4WzJVBI7wu_Jqku2_y1xq_kzymumh/view?usp=drive_link. Take a try!

**Comment by sfchng** [comment]
Thanks for sharing the plant dataset. Is it possible to provide the configuration files as well?

**Comment by RainbowRui** [comment]
You can use the default configure file for training!

**Comment by sfchng** [comment]
Thanks for the response! In the open review, you mentioned that sequences used for Fig. 6 does not require robust-ICP based camera pose initialization. I wonder if you can also share the sequences used for Fig. 6.

**Comment by RainbowRui** [comment]
Given the changes in my work, it is currently inconvenient for me to organize new sequence data. I suggest that you can directly use the robust ICP method to initialize the data.
