### ISSUE TITLE
extract_canonical_geometry function is missing arguments

### ISSUE THREAD

**Issue by NKadvil** [USTC3DV/NDR-code#12]
I'm trying to extract and visualize the canonical mesh, I saw that there's a function called validate_canonical_mesh which calls the extract_canonical_geometry. 
The query function for the extract_canonical_geometry is lambda pts: -self.sdf_network.sdf(pts, alpha_ratio)) and it is missing the argument of topo_coord. 

Is there a way to extract the canonical mesh? Are there values of topo_coord I can insert to the sdf which won't change the canonical mesh?

Thanks!

**Comment by RainbowRui** [comment]
Since the canonical space is not a 3D space but a higher-dimensional space, extracting an exact canonical mesh is not straightforward.

**Comment by NKadvil** [comment]
Thanks! 
I just saw the extract_canonical_geometry function and assumed that it might be possible. 
Closing the issue :)
