### ISSUE TITLE
Goal of pose_initialization

### ISSUE THREAD

**Issue by ShunkaiZhou** [USTC3DV/NDR-code#13]
Hi, thank you for the excellent work. I want to know the goal of pose_initialization? Does he have an alternative?
Thank you very much.

**Comment by ShunkaiZhou** [comment]
> Hi, its goal is to eliminate the error of locations of different frames projected in canonical space. The alternative methods are other rigid/non-rigid registration algorithms.

Thank you very much. 

When I run the code using my own realsense dataset, I am a bit confused as to what the steps are. May I ask if the running process can be summarized as the following steps:

1.Shoot our own dataset and get the same RGB, Depth, Mask as the original dataset format.
2.With the help of Colmap, generate npz file like NeUS
3.Run

May I ask if pose_initialization is part of the second step to help us generate the npz file?
Thank you very much for your patience in replying.

**Comment by RainbowRui** [comment]
Yes.

**Comment by ShunkaiZhou** [comment]
OK. Thank you very much
