### ISSUE TITLE
Preprocessed data for remaining sequences of KillingFusion

### ISSUE THREAD

**Issue by SDNAFIO** [USTC3DV/NDR-code#3]
Is it possible to also upload the preprocessed data for the remaining sequences of the KillingFusion dataset, e.g., "Alex", "Hat"?
I would really appreciate it.

**Comment by SDNAFIO** [comment]
Additionally, it would also be nice if you could provide the respective .conf files.
For example, for the frog sequence, the preprocessed dataset is provided, but the .conf file is missing.

**Comment by RainbowRui** [comment]
The link is here: https://drive.google.com/file/d/11w-5tCqOv8xwmIgBeJVFMH8hkJpT86iu/view?usp=drive_link. You could mimic the setting as we provided before (human body or daily necessities). Take a try!
