### ISSUE TITLE
Quality of the camera poses

### ISSUE THREAD

**Issue by LifeBeyondExpectations** [USTC3DV/NDR-code#7]
Thank you for sharing the implementation. I have a question regarding the quality of the given camera poses.
It seems like the authors manually calculate the camera poses as below,

<img width="1476" alt="Screenshot 2023-02-07 at 1 48 44 PM" src="https://user-images.githubusercontent.com/32631453/217374666-b664d6fd-cec9-40f0-8dd3-fe6a1a27f65b.png">

Then, the authors refine the camera poses by making them trainable parameters.
https://github.com/USTC3DV/NDR-code/blob/f842e415ee9c48f391b183265a192e2b3d533f90/confs/kfusion_toy.conf#L23
__Is there any reason behind this kind of system setup?__

When I naively visualize point cloud from the origin dataset, the result looks as below,

<img width="1338" alt="Screenshot 2023-02-07 at 1 53 09 PM" src="https://user-images.githubusercontent.com/32631453/217375250-c69b7cc4-d4e2-489a-aeef-169fdef38601.png">

I personally guess that the authors intentionally fit the camera poses in an object-centric manner. 
Any comment will be welcomed.

**Comment by Guptajakala** [comment]
@LifeBeyondExpectations 
I guess the author didn't manually align, but use this step https://github.com/USTC3DV/NDR-code/blob/main/pose_initialization/README.md
Did you try that to see if it can reproduce the similar alignment?
